server:
  port: ":8080"

auth:
  base_url: "http://auth-generator:8080"

database:
  host: "postgres-2"
  port: 5432
  user: "admin"
  password: "password"
  name: "user_db"

grpc:
  currency_service_url: "currency:8090"
